apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30130
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: meu-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
