apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meu-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
        ports:
          - containerPort: 80
